import type { Tool } from "./types";

/**
 * Single source of truth for every PDFKit tool.
 *
 * Everything else in the application — homepage, search, category pages,
 * navigation, footer and tool pages — reads from this array. Nothing here is
 * duplicated anywhere else.
 *
 * IMPORTANT: no tool may be marked `AVAILABLE` until its processing is really
 * implemented. A tool is only `AVAILABLE` when it has a registered processor in
 * `src/lib/processing/registry.ts`; a test enforces that both sides agree.
 *
 * Implemented today: Merge PDF, Split PDF, Extract PDF Pages, Delete PDF Pages,
 * Reorder PDF Pages, Rotate PDF, Compress PDF, Images to PDF, PNG to PDF,
 * PDF to JPG, PDF to PNG, PDF to Word, Edit PDF Metadata, Remove Metadata
 * and Watermark. Page Numbers (Phase 22), Crop (Phase 24) and Flatten PDF
 * (Phase 26), too, are implemented. Everything else is `COMING_SOON`.
 */

const PDF_EXT = [".pdf"];
const PDF_MIME = ["application/pdf"];

function pdfTool(
  tool: Omit<Tool, "supportedFileTypes" | "acceptedMimeTypes" | "route" | "status"> &
    Partial<Pick<Tool, "supportedFileTypes" | "acceptedMimeTypes" | "status">>,
): Tool {
  return {
    route: `/tools/${tool.id}`,
    status: "COMING_SOON",
    supportedFileTypes: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    ...tool,
  };
}

export const TOOLS: readonly Tool[] = [
  /* ------------------------------------------------------------------ */
  /* Organize PDF                                                        */
  /* ------------------------------------------------------------------ */
  pdfTool({
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one ordered document.",
    category: "organize",
    icon: "merge",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["combine", "join", "concatenate", "append"],
    howItWorks: [
      "Add the PDF files you want to combine.",
      "Arrange them in the order the final document should follow.",
      "Merge them and download a single PDF.",
    ],
  }),
  pdfTool({
    id: "split-pdf",
    name: "Split PDF",
    description: "Divide one PDF into separate documents by page ranges.",
    category: "organize",
    icon: "split",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["divide", "separate", "cut", "ranges", "pages", "extract"],
    howItWorks: [
      "Upload the PDF you want to split.",
      "Split every page, or enter page ranges such as 1-3, 4-6.",
      "Download the resulting PDFs.",
    ],
  }),
  pdfTool({
    id: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size while keeping the document readable.",
    category: "organize",
    icon: "compress",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["optimize", "shrink", "reduce size", "smaller"],
    howItWorks: [
      "Upload the PDF you want to make smaller.",
      "Pick how strongly the file should be compressed.",
      "Download the optimised document.",
    ],
  }),
  pdfTool({
    id: "rotate-pdf",
    name: "Rotate PDF",
    description: "Turn selected pages so every page faces the right way.",
    category: "organize",
    icon: "rotate",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["turn", "orientation", "landscape", "portrait", "sideways"],
    howItWorks: [
      "Upload the PDF with pages facing the wrong way.",
      "Rotate individual pages, or rotate them all at once.",
      "Download the corrected PDF.",
    ],
  }),
  pdfTool({
    id: "delete-pdf-pages",
    name: "Delete PDF Pages",
    description: "Remove pages you do not need from a PDF document.",
    category: "organize",
    icon: "trash",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["remove pages", "erase", "drop pages", "delete"],
    howItWorks: [
      "Upload your PDF.",
      "Enter the pages to remove, such as 2, 4, 7-9.",
      "Download the PDF without those pages.",
    ],
  }),
  pdfTool({
    id: "reorder-pdf-pages",
    name: "Reorder PDF Pages",
    description: "Drag pages into a new order inside the same document.",
    category: "organize",
    icon: "reorder",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["rearrange", "sort pages", "move pages", "organise", "organize"],
    howItWorks: [
      "Upload your PDF and see a preview of every page.",
      "Drag the pages, or use the arrow buttons, until the order is right.",
      "Download the reordered document.",
    ],
  }),
  pdfTool({
    id: "organize-pdf",
    name: "Organize PDF",
    description: "Reorder, rotate and delete pages in a single visual workflow.",
    category: "organize",
    icon: "reorder",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["reorder", "rotate", "delete pages", "rearrange", "organise", "organize"],
    howItWorks: [
      "Upload your PDF and see previews of every page.",
      "Drag or reorder pages, rotate pages, or remove pages you do not need.",
      "Download the organized PDF.",
    ],
  }),
  pdfTool({
    id: "extract-pdf-pages",
    name: "Extract PDF Pages",
    description: "Pull selected pages out of a PDF into a new file.",
    category: "organize",
    icon: "extract",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["pick pages", "copy pages", "subset", "keep pages"],
    howItWorks: [
      "Upload the source PDF.",
      "Enter the pages to keep, such as 1-3, 5, 8-10.",
      "Download them as one new PDF.",
    ],
  }),

  /* ------------------------------------------------------------------ */
  /* Convert                                                             */
  /* ------------------------------------------------------------------ */
  pdfTool({
    id: "images-to-pdf",
    name: "Images to PDF",
    description: "Turn JPG and PNG images into a single PDF document.",
    category: "convert",
    icon: "image",
    status: "AVAILABLE",
    plannedTier: "free",
    supportedFileTypes: [".jpg", ".jpeg", ".png"],
    acceptedMimeTypes: ["image/jpeg", "image/png"],
    keywords: ["jpeg", "photo", "picture", "image to pdf", "png to pdf", "jpg to pdf"],
    howItWorks: [
      "Add the JPG or PNG images you want to include.",
      "Arrange them in the order the pages should follow.",
      "Download one PDF with exactly one page per image.",
    ],
  }),
  pdfTool({
    id: "png-to-pdf",
    name: "PNG to PDF",
    description: "Turn PNG images into a single PDF document.",
    category: "convert",
    icon: "image",
    status: "AVAILABLE",
    plannedTier: "free",
    supportedFileTypes: [".png"],
    acceptedMimeTypes: ["image/png"],
    keywords: ["screenshot", "picture", "image to pdf", "transparent"],
    howItWorks: [
      "Add the PNG images you want to include.",
      "Arrange them in the order the pages should follow.",
      "Download one PDF with exactly one page per image.",
    ],
  }),
  pdfTool({
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Export every page of a PDF as a JPG image.",
    category: "convert",
    icon: "image",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["jpeg", "export images", "page images", "screenshot"],
    howItWorks: [
      "Upload the PDF you want to export.",
      "Every page is rendered at 150 DPI (server-configurable).",
      "Download one JPG, or a ZIP with one JPG per page.",
    ],
  }),
  pdfTool({
    id: "pdf-to-png",
    name: "PDF to PNG",
    description: "Export PDF pages as lossless PNG images.",
    category: "convert",
    icon: "image",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["export images", "page images", "lossless"],
    howItWorks: [
      "Upload the PDF you want to export.",
      "Every page is rendered at 150 DPI (server-configurable).",
      "Download one PNG, or a ZIP with one PNG per page.",
    ],
  }),
  pdfTool({
    id: "pdf-to-word",
    name: "PDF to Word",
    description:
      "Extract the text of a PDF into an editable Word document.",
    category: "convert",
    icon: "word",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["docx", "editable", "microsoft word", "text"],
    howItWorks: [
      "Upload the PDF whose text you need in Word.",
      "Every page's text is extracted in order, one paragraph per line.",
      "Download a .docx file. Text only — formatting, images, tables and exact layout are not preserved.",
    ],
  }),
  pdfTool({
    id: "extract-images",
    name: "Extract Images",
    description: "Extract embedded raster images from PDF pages.",
    category: "convert",
    icon: "image",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["extract photos", "pictures", "save images", "embedded images"],
    howItWorks: [
      "Upload the PDF document.",
      "Select pages to extract images from.",
      "Download extracted JPG/PNG images directly or as a ZIP.",
    ],
  }),
  pdfTool({
    id: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract plain searchable text from PDF pages.",
    category: "convert",
    icon: "text",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["txt", "plain text", "extract text", "save text"],
    howItWorks: [
      "Upload the PDF document.",
      "Select pages to extract text from.",
      "Download a .txt file containing the page text. Scanned pages contain no text — OCR is NOT performed.",
    ],
  }),
  pdfTool({
    id: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert Word documents into shareable PDF files.",
    category: "convert",
    icon: "word",
    plannedTier: "free",
    supportedFileTypes: [".doc", ".docx"],
    acceptedMimeTypes: [
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ],
    keywords: ["docx", "microsoft word", "document to pdf"],
    howItWorks: [
      "Upload your .doc or .docx file.",
      "PDFKit renders it with the original layout.",
      "Download the PDF.",
    ],
  }),
  pdfTool({
    id: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Turn tables inside a PDF into an Excel spreadsheet.",
    category: "convert",
    icon: "excel",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["xlsx", "spreadsheet", "tables", "data"],
    howItWorks: [
      "Upload a PDF that contains tabular data.",
      "Check the detected tables.",
      "Download the .xlsx spreadsheet.",
    ],
  }),
  pdfTool({
    id: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert spreadsheets into clean, printable PDFs.",
    category: "convert",
    icon: "excel",
    plannedTier: "free",
    supportedFileTypes: [".xls", ".xlsx"],
    acceptedMimeTypes: [
      "application/vnd.ms-excel",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ],
    keywords: ["xlsx", "spreadsheet", "sheet to pdf"],
    howItWorks: [
      "Upload your .xls or .xlsx file.",
      "Choose orientation and scaling.",
      "Download the PDF.",
    ],
  }),
  pdfTool({
    id: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    description: "Convert slide decks into PDFs that open anywhere.",
    category: "convert",
    icon: "powerpoint",
    plannedTier: "free",
    supportedFileTypes: [".ppt", ".pptx"],
    acceptedMimeTypes: [
      "application/vnd.ms-powerpoint",
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ],
    keywords: ["pptx", "slides", "presentation", "deck"],
    howItWorks: [
      "Upload your .ppt or .pptx deck.",
      "Choose whether to include speaker notes.",
      "Download the PDF.",
    ],
  }),

  /* ------------------------------------------------------------------ */
  /* Edit PDF                                                            */
  /* ------------------------------------------------------------------ */
  pdfTool({
    id: "add-text",
    name: "Add Text",
    description: "Place a text box on any page of a PDF.",
    category: "edit",
    icon: "text",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["write", "type", "fill form", "insert text"],
    howItWorks: [
      "Upload the PDF you want to write on.",
      "Type the text and pick a position, size and pages.",
      "Download the PDF with the text added as real, searchable text.",
    ],
  }),
  pdfTool({
    id: "add-images",
    name: "Add Images",
    description: "Insert logos, photos or stamps into a PDF page.",
    category: "edit",
    icon: "image",
    status: "AVAILABLE",
    plannedTier: "free",
    supportedFileTypes: [".pdf", ".jpg", ".jpeg", ".png"],
    acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    keywords: ["insert image", "logo", "stamp", "picture"],
    howItWorks: [
      "Upload the PDF and the image (JPG or PNG) you want to place.",
      "Position and resize the image.",
      "Download the edited PDF.",
    ],
  }),
  pdfTool({
    id: "draw",
    name: "Draw",
    description: "Draw freehand lines and marks directly on a document.",
    category: "edit",
    icon: "draw",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["freehand", "pen", "sketch", "sign by hand"],
    howItWorks: [
      "Upload your PDF.",
      "Draw vector strokes on the page.",
      "Download the edited PDF.",
    ],
  }),
  pdfTool({
    id: "highlight",
    name: "Highlight",
    description: "Mark important passages with a highlighter.",
    category: "edit",
    icon: "highlight",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["marker", "emphasise", "colour text"],
    howItWorks: [
      "Upload your PDF.",
      "Select the area you want to highlight.",
      "Download the marked-up PDF. Highlighting is a visual overlay — it does NOT remove content.",
    ],
  }),
  pdfTool({
    id: "add-shapes",
    name: "Add Shapes",
    description: "Add rectangles, circles, lines and arrows to a page.",
    category: "edit",
    icon: "shapes",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["rectangle", "circle", "arrow", "line", "box"],
    howItWorks: [
      "Upload your PDF.",
      "Draw shapes and set their colour and thickness.",
      "Download the edited PDF.",
    ],
  }),
  pdfTool({
    id: "watermark",
    name: "Watermark",
    description: "Stamp a text watermark across the pages of a PDF.",
    category: "edit",
    icon: "watermark",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["stamp", "draft", "confidential", "branding"],
    howItWorks: [
      "Upload the PDF you want to stamp.",
      "Type the watermark text and pick opacity, angle, placement and pages.",
      "Download the watermarked PDF. A visible watermark is a deterrent, not protection.",
    ],
  }),
  pdfTool({
    id: "page-numbers",
    name: "Page Numbers",
    description: "Add page numbers to the pages of a PDF.",
    category: "edit",
    icon: "page-numbers",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["numbering", "footer", "index", "pagination"],
    howItWorks: [
      "Upload the PDF you want to number.",
      "Pick position, starting number, font size, format and pages.",
      "Download the numbered PDF. The numbers are ordinary visible text.",
    ],
  }),
  pdfTool({
    id: "crop",
    name: "Crop",
    description:
      "Trim margins or crop selected pages by area. Cropping changes what is visible, but does not remove hidden content.",
    category: "edit",
    icon: "crop",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["trim", "margins", "resize page", "cut edges"],
    howItWorks: [
      "Upload the PDF and choose pages.",
      "Crop by rectangle or by margins, in points from a bottom-left origin.",
      "Download the cropped PDF. Cropping hides content from view — it does not remove it.",
    ],
  }),
  pdfTool({
    id: "flatten-pdf",
    name: "Flatten PDF",
    description:
      "Flatten PDF forms into permanent page content. Field values remain selectable; links stay clickable. Signed PDFs are rejected, and document scripts are not removed.",
    category: "edit",
    icon: "flatten",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["form", "fields", "acroform", "make read-only", "burn in"],
    howItWorks: [
      "Upload the PDF form you want to flatten.",
      "Review the warning: flattening is permanent — fields stop being editable.",
      "Download the flattened PDF. Values stay selectable; document scripts are not removed.",
    ],
  }),
  pdfTool({
    id: "annotations",
    name: "Annotations",
    description: "Add comments and notes for review and feedback.",
    category: "edit",
    icon: "annotate",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["comment", "notes", "review", "feedback", "sticky note", "hyperlink", "link"],
    howItWorks: [
      "Upload the PDF you want to annotate.",
      "Add sticky note comments or web links.",
      "Download the annotated PDF with native PDF annotations embedded.",
    ],
  }),

  pdfTool({
    id: "edit-pdf-metadata",
    name: "Edit PDF Metadata",
    description: "View and change a document's title, author and keywords.",
    category: "edit",
    icon: "metadata",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["title", "author", "subject", "keywords", "properties", "info"],
    howItWorks: [
      "Upload the PDF and see its current properties.",
      "Edit title, author, subject, keywords or creator — or clear them.",
      "Download the updated PDF with every page unchanged.",
    ],
  }),

  /* ------------------------------------------------------------------ */
  /* Security                                                            */
  /* ------------------------------------------------------------------ */
  pdfTool({
    id: "password-protect",
    name: "Password Protect",
    description: "Encrypt a PDF so only people with the password can open it.",
    category: "security",
    icon: "lock",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["encrypt", "password", "secure", "protect"],
    howItWorks: [
      "Upload the PDF you want to protect.",
      "Set the password that will be required to open the document.",
      "Download the protected PDF — opening it asks for that password.",
    ],
  }),
  pdfTool({
    id: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove a password you own from a protected PDF.",
    category: "security",
    icon: "unlock",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["decrypt", "remove password", "open protected"],
    howItWorks: [
      "Upload the protected PDF.",
      "Enter the password you already have for the file.",
      "Download the unlocked PDF — an ordinary document again.",
    ],
  }),
  pdfTool({
    id: "redact-information",
    name: "Redact Information",
    description: "Place vector blackout boxes over sensitive page areas. Blackout boxes cover visible content on the page canvas.",
    category: "security",
    icon: "redact",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["black out", "hide", "censor", "sensitive", "gdpr"],
    howItWorks: [
      "Upload the document that contains sensitive content.",
      "Mark the page areas to cover with blackout boxes.",
      "Download a PDF with those areas covered by vector blackout rectangles. Note: Blackout rectangles cover visible content on the rendered page — underlying text streams are not stripped.",
    ],
  }),
  pdfTool({
    id: "digital-signature",
    name: "Digital Signature",
    description: "Sign a document or request a signature from someone else.",
    category: "security",
    icon: "signature",
    plannedTier: "pro",
    keywords: ["esign", "sign", "signature", "contract"],
    howItWorks: [
      "Upload the document to sign.",
      "Place the signature fields on the page.",
      "Download the signed PDF.",
    ],
  }),
  pdfTool({
    id: "remove-metadata",
    name: "Remove Metadata",
    description: "Strip title, author, keywords and XMP data from a PDF.",
    category: "security",
    icon: "metadata",
    status: "AVAILABLE",
    plannedTier: "free",
    keywords: ["privacy", "exif", "clean", "author", "hidden data", "title", "keywords"],
    howItWorks: [
      "Upload your PDF and see the metadata it contains.",
      "The title, author, subject, keywords, creator and XMP data are removed.",
      "Download the cleaned PDF — every page stays exactly as it was.",
    ],
  }),

  /* ------------------------------------------------------------------ */
  /* OCR                                                                 */
  /* ------------------------------------------------------------------ */
  pdfTool({
    id: "image-to-text",
    name: "Image to Text",
    description: "Read the text contained in a photo or screenshot.",
    category: "ocr",
    icon: "scan",
    plannedTier: "free",
    supportedFileTypes: [".jpg", ".jpeg", ".png", ".webp"],
    acceptedMimeTypes: ["image/jpeg", "image/png", "image/webp"],
    keywords: ["ocr", "recognise text", "extract text", "photo"],
    howItWorks: [
      "Upload an image that contains text.",
      "Choose the language of the document.",
      "Copy or download the recognised text.",
    ],
  }),
  pdfTool({
    id: "scanned-pdf-to-searchable-pdf",
    name: "Scanned PDF to Searchable PDF",
    description: "Add a text layer to a scan so it becomes searchable.",
    category: "ocr",
    icon: "scan",
    plannedTier: "free",
    keywords: ["ocr", "searchable", "scan", "text layer", "index"],
    howItWorks: [
      "Upload a scanned PDF.",
      "Choose the document language.",
      "Download a PDF whose text can be searched and selected.",
    ],
  }),
  pdfTool({
    id: "ocr-document",
    name: "OCR Document",
    description: "Extract plain text from a document for reuse elsewhere.",
    category: "ocr",
    icon: "text",
    plannedTier: "free",
    supportedFileTypes: [".pdf", ".jpg", ".jpeg", ".png"],
    acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png"],
    keywords: ["ocr", "text extraction", "recognise", "plain text"],
    howItWorks: [
      "Upload a PDF or image.",
      "Choose the document language.",
      "Download the extracted text.",
    ],
  }),

  /* ------------------------------------------------------------------ */
  /* AI                                                                  */
  /* ------------------------------------------------------------------ */
  pdfTool({
    id: "summarize-pdf",
    name: "Summarize PDF",
    description: "Get a short summary of a long document.",
    category: "ai",
    icon: "ai-summarize",
    plannedTier: "pro",
    keywords: ["summary", "tldr", "shorten", "overview", "ai"],
    howItWorks: [
      "Upload the document you need to understand quickly.",
      "Choose how detailed the summary should be.",
      "Read or download the summary.",
    ],
  }),
  pdfTool({
    id: "ask-pdf",
    name: "Ask PDF",
    description: "Ask questions about a document and get sourced answers.",
    category: "ai",
    icon: "ask",
    plannedTier: "pro",
    keywords: ["chat", "question", "ai", "q&a", "search document"],
    howItWorks: [
      "Upload the document you have questions about.",
      "Ask a question in plain language.",
      "Read the answer with references to the pages it came from.",
    ],
  }),
  pdfTool({
    id: "extract-important-information",
    name: "Extract Important Information",
    description: "Pull out the key facts, names and figures from a document.",
    category: "ai",
    icon: "key-points",
    plannedTier: "pro",
    keywords: ["entities", "facts", "data extraction", "ai", "fields"],
    howItWorks: [
      "Upload the document.",
      "Choose the kind of information you need.",
      "Review and export the extracted fields.",
    ],
  }),
  pdfTool({
    id: "extract-tables",
    name: "Extract Tables",
    description: "Detect tables in a document and export them as data.",
    category: "ai",
    icon: "table",
    status: "AVAILABLE",
    plannedTier: "pro",
    keywords: ["csv", "spreadsheet", "rows", "columns", "data"],
    howItWorks: [
      "Upload a document containing tables.",
      "Check the detected table boundaries.",
      "Export the tables as CSV or XLSX.",
    ],
  }),
  pdfTool({
    id: "generate-notes",
    name: "Generate Notes",
    description: "Turn a document into structured study or meeting notes.",
    category: "ai",
    icon: "ai-notes",
    plannedTier: "pro",
    keywords: ["study", "revision", "outline", "ai", "notes"],
    howItWorks: [
      "Upload the document.",
      "Choose the note style you want.",
      "Download the generated notes.",
    ],
  }),
  pdfTool({
    id: "generate-key-points",
    name: "Generate Key Points",
    description: "Reduce a document to a list of its main points.",
    category: "ai",
    icon: "list-checks",
    plannedTier: "pro",
    keywords: ["bullets", "highlights", "main ideas", "ai"],
    howItWorks: [
      "Upload the document.",
      "Choose how many points you want.",
      "Copy or download the list.",
    ],
  }),
  pdfTool({
    id: "extract-dates-and-deadlines",
    name: "Extract Dates and Deadlines",
    description: "Find dates, deadlines and obligations inside a document.",
    category: "ai",
    icon: "calendar",
    plannedTier: "pro",
    keywords: ["calendar", "due date", "contract", "schedule", "ai"],
    howItWorks: [
      "Upload a contract, invoice or plan.",
      "Review the dates PDFKit found and where they appear.",
      "Export them as a list.",
    ],
  }),
  pdfTool({
    id: "translate-documents",
    name: "Translate Documents",
    description: "Translate a document while keeping its structure.",
    category: "ai",
    icon: "translate",
    plannedTier: "pro",
    keywords: ["language", "translation", "localise", "ai"],
    howItWorks: [
      "Upload the document to translate.",
      "Choose the target language.",
      "Download the translated document.",
    ],
  }),
  pdfTool({
    id: "compare-documents",
    name: "Compare Documents",
    description: "See what changed between two versions of a document.",
    category: "ai",
    icon: "ai-compare",
    status: "AVAILABLE",
    plannedTier: "pro",
    keywords: ["diff", "changes", "versions", "redline", "ai"],
    howItWorks: [
      "Upload the two versions you want to compare.",
      "Review the differences side by side.",
      "Export a report of the changes.",
    ],
  }),
] as const;

/** Tool ids highlighted on the homepage, in display order. */
export const POPULAR_TOOL_IDS = [
  "merge-pdf",
  "split-pdf",
  "compress-pdf",
  "rotate-pdf",
  "delete-pdf-pages",
  "extract-pdf-pages",
  "images-to-pdf",
  "pdf-to-jpg",
] as const;
